name: Build Kernel - Xiaomi xuanyuan

on:
  workflow_d

jobs:
  build:
    name: Build xuanyuan Kernel
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Set up Dependencies
        run: |
          sudo apt up
          sudo apt install -y bc bison build-essential ccache curl flex git gnupg \
            libncurses5-dev libssl-dev libelf-dev lzop python3 rsync unzip wget zip zlib1g-dev \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Download Clang 18.1.3 (Neutron)
        run: |
          mkdir clang
          curl -L -o Clang-1
          
    8.1.3.tar.gz https://github.com/Neutron-Toolchains/clang-build-catalogue/releases/download/18.1.3/Clang-18.1.3.tar.gz
          tar -xf Clang-18.1.3.tar.gz -C clang --strip-components=1

      - name: Set Environment Variables
        run: |
          echo "ARCH=arm> $GITHUB_ENV
          echo "SUBARCH=arm64" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=GitHubCI" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=github" >> $GITHUB_ENV
          echo "${GITHUB_WORKSPACE}/clang/bin" >> $GITHUB_PATH

      - name: Build Kernel
        run: |
          make O=out ARCH=arm64 vendor/xuanyuan_defconfig
          make -j$(nproc) O=out \
            ARCH=arm64 \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LLVM=1

      - name: Upload Kernel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xuanyuan-kernel
          path: |
            out/arch/arm64/boot/Image*
            out/arch/arm64/boot/dtbo.img
